### ISSUE TITLE
gernamium/germanium spelling inconsistencies

### ISSUE THREAD

**Issue by rcjwoods** [argonnexraydetector/ADGernamiumStrip#2]
/ADGermaniumStrip-1-0/iocs/gernamiumStripIOC
/ADGermaniumStrip-1-0/iocs/gernamiumStripIOC/gernamiumStripApp
/ADGermaniumStrip-1-0/iocs/Makefile
/ADGermaniumStrip-1-0/iocs/gernamiumStripIOC/iocBoot/iocGernamiumStrip

This could be causing build problems... not sure yet, but it should be fixed.

**Comment by antoninomiceli** [comment]
Sorry. This is my fault. I guess I did not fix the typo everywhere!

On Feb 9, 2018, at 12:36 PM, Russell Woods <notifications@github.com<mailto:notifications@github.com>> wrote:


/ADGermaniumStrip-1-0/iocs/gernamiumStripIOC
/ADGermaniumStrip-1-0/iocs/gernamiumStripIOC/gernamiumStripApp

This could be causing build problems... not sure yet, but it should be fixed.

**Comment by rcjwoods** [comment]
This is fixed.
